function runILDPreferencePlots(allData, opts)

% runILDPreferencePlots
%
% Example:
%   opts = struct();
%   opts.whichSub = "dataAllSub";
%   opts.whichModel = 5;
%   opts.scale = 'lin';   % 'lin' or 'log'
%   opts.baseMapNames = baseMapNames;
%   opts.hemispheres = hemispheres;
%   opts.baseModelNames = baseModelNames;
%   opts.baseDTnames = baseDTnames;
%   opts.whichDT = whichDT;
%   opts.veThresh = veThresh;
%   runILDPreferencePlots(allData, opts);

    if nargin < 2 || isempty(opts)
        opts = struct();
    end

    % -------- validate scale --------
    if ~(strcmpi(opts.scale, 'lin') || strcmpi(opts.scale, 'log'))
        error('opts.scale must be ''lin'' or ''log''.');
    end

    % standardize scale text
    opts.scale = lower(opts.scale);
    
    % -------- run plots --------
    ILDPreferenceHist( ...
        allData, ...
        opts.whichSub, ...
        opts.baseMapNames, ...
        opts.hemispheres, ...
        opts.baseModelNames, ...
        opts.whichModel, ...
        opts.baseDTnames, ...
        opts.whichDT, ...
        opts.veThresh, ...
        opts.scale,...
        opts.exp);
    if opts.vesPlot
        VE_ILDPreferenceHist( ...
            allData, ...
            opts.whichSub, ...
            opts.baseMapNames, ...
            opts.hemispheres, ...
            opts.baseModelNames, ...
            opts.whichModel, ...
            opts.baseDTnames, ...
            opts.whichDT, ...
            opts.veThresh, ...
            opts.scale);
    end
end